[package]
name = "rustbac-mstp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "BACnet MS/TP data link layer over RS-485 serial"
repository = "https://github.com/rbhans/rust-bac"

[features]
default = ["std"]
std = ["rustbac-datalink/std", "dep:tokio", "dep:tokio-serial", "dep:log", "alloc"]
alloc = ["rustbac-datalink/alloc"]

[dependencies]
rustbac-datalink = { path = "../rustbac-datalink", version = "0.4.1", default-features = false }
tokio = { version = "1", features = ["rt", "time", "sync", "io-util"], optional = true }
tokio-serial = { version = "5", optional = true }
log = { version = "0.4", optional = true }
