/// BACnet property identifiers.
///
/// Common standard properties are named variants; vendor-specific or
/// unrecognised identifiers use [`Proprietary`](Self::Proprietary).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub enum PropertyId {
    AckedTransitions,
    ActiveText,
    ApduTimeout,
    ApplicationSoftwareVersion,
    BufferSize,
    CovIncrement,
    DatabaseRevision,
    DateList,
    Deadband,
    Description,
    EffectivePeriod,
    Enable,
    EventEnable,
    EventState,
    EventTimeStamps,
    ExceptionSchedule,
    FirmwareRevision,
    HighLimit,
    InactiveText,
    LimitEnable,
    ListOfObjectPropertyReferences,
    LogBuffer,
    LogDeviceObjectProperty,
    LogInterval,
    LowLimit,
    MaxApduLengthAccepted,
    MaxPresValue,
    MinPresValue,
    ModelName,
    NotificationClass,
    NotifyType,
    NumberOfApduRetries,
    ObjectIdentifier,
    ObjectList,
    ObjectName,
    ObjectType,
    OutOfService,
    PresentValue,
    PriorityArray,
    ProtocolRevision,
    ProtocolVersion,
    RecipientList,
    RecordCount,
    Reliability,
    RelinquishDefault,
    Resolution,
    ScheduleDefault,
    SegmentationSupported,
    StartTime,
    StatusFlags,
    StopTime,
    SystemStatus,
    TimeDelay,
    TotalRecordCount,
    Units,
    UpdateInterval,
    VendorName,
    WeeklySchedule,
    Proprietary(u32),
}

impl PropertyId {
    pub const fn to_u32(self) -> u32 {
        match self {
            Self::AckedTransitions => 0,
            Self::ActiveText => 4,
            Self::ApduTimeout => 11,
            Self::ApplicationSoftwareVersion => 12,
            Self::BufferSize => 126,
            Self::CovIncrement => 22,
            Self::DatabaseRevision => 155,
            Self::DateList => 23,
            Self::Deadband => 25,
            Self::Description => 28,
            Self::EffectivePeriod => 32,
            Self::Enable => 133,
            Self::EventEnable => 35,
            Self::EventState => 36,
            Self::EventTimeStamps => 130,
            Self::ExceptionSchedule => 38,
            Self::FirmwareRevision => 44,
            Self::HighLimit => 45,
            Self::InactiveText => 46,
            Self::LimitEnable => 52,
            Self::ListOfObjectPropertyReferences => 78,
            Self::LogBuffer => 131,
            Self::LogDeviceObjectProperty => 132,
            Self::LogInterval => 134,
            Self::LowLimit => 59,
            Self::MaxApduLengthAccepted => 62,
            Self::MaxPresValue => 65,
            Self::MinPresValue => 69,
            Self::ModelName => 70,
            Self::NotificationClass => 17,
            Self::NotifyType => 72,
            Self::NumberOfApduRetries => 73,
            Self::ObjectIdentifier => 75,
            Self::ObjectList => 76,
            Self::ObjectName => 77,
            Self::ObjectType => 79,
            Self::OutOfService => 81,
            Self::PresentValue => 85,
            Self::PriorityArray => 87,
            Self::ProtocolRevision => 139,
            Self::ProtocolVersion => 98,
            Self::RecipientList => 102,
            Self::RecordCount => 141,
            Self::Reliability => 103,
            Self::RelinquishDefault => 104,
            Self::Resolution => 106,
            Self::ScheduleDefault => 174,
            Self::SegmentationSupported => 107,
            Self::StartTime => 142,
            Self::StatusFlags => 111,
            Self::StopTime => 143,
            Self::SystemStatus => 112,
            Self::TimeDelay => 113,
            Self::TotalRecordCount => 145,
            Self::Units => 117,
            Self::UpdateInterval => 118,
            Self::VendorName => 121,
            Self::WeeklySchedule => 123,
            Self::Proprietary(v) => v,
        }
    }

    pub const fn from_u32(value: u32) -> Self {
        match value {
            0 => Self::AckedTransitions,
            4 => Self::ActiveText,
            11 => Self::ApduTimeout,
            12 => Self::ApplicationSoftwareVersion,
            126 => Self::BufferSize,
            22 => Self::CovIncrement,
            155 => Self::DatabaseRevision,
            23 => Self::DateList,
            25 => Self::Deadband,
            28 => Self::Description,
            32 => Self::EffectivePeriod,
            133 => Self::Enable,
            35 => Self::EventEnable,
            36 => Self::EventState,
            130 => Self::EventTimeStamps,
            38 => Self::ExceptionSchedule,
            44 => Self::FirmwareRevision,
            45 => Self::HighLimit,
            46 => Self::InactiveText,
            52 => Self::LimitEnable,
            78 => Self::ListOfObjectPropertyReferences,
            131 => Self::LogBuffer,
            132 => Self::LogDeviceObjectProperty,
            134 => Self::LogInterval,
            59 => Self::LowLimit,
            62 => Self::MaxApduLengthAccepted,
            65 => Self::MaxPresValue,
            69 => Self::MinPresValue,
            70 => Self::ModelName,
            17 => Self::NotificationClass,
            72 => Self::NotifyType,
            73 => Self::NumberOfApduRetries,
            75 => Self::ObjectIdentifier,
            76 => Self::ObjectList,
            77 => Self::ObjectName,
            79 => Self::ObjectType,
            81 => Self::OutOfService,
            85 => Self::PresentValue,
            87 => Self::PriorityArray,
            139 => Self::ProtocolRevision,
            98 => Self::ProtocolVersion,
            102 => Self::RecipientList,
            141 => Self::RecordCount,
            103 => Self::Reliability,
            104 => Self::RelinquishDefault,
            106 => Self::Resolution,
            174 => Self::ScheduleDefault,
            107 => Self::SegmentationSupported,
            142 => Self::StartTime,
            111 => Self::StatusFlags,
            143 => Self::StopTime,
            112 => Self::SystemStatus,
            113 => Self::TimeDelay,
            145 => Self::TotalRecordCount,
            117 => Self::Units,
            118 => Self::UpdateInterval,
            121 => Self::VendorName,
            123 => Self::WeeklySchedule,
            v => Self::Proprietary(v),
        }
    }

    /// Parse a BACnet hyphenated property name (e.g. `"present-value"`) into a `PropertyId`.
    ///
    /// Returns `None` for unrecognised names. Proprietary properties cannot be
    /// round-tripped through this method; use [`from_u32`](Self::from_u32) instead.
    pub fn from_name(name: &str) -> Option<Self> {
        match name {
            "acked-transitions" => Some(Self::AckedTransitions),
            "active-text" => Some(Self::ActiveText),
            "apdu-timeout" => Some(Self::ApduTimeout),
            "application-software-version" => Some(Self::ApplicationSoftwareVersion),
            "buffer-size" => Some(Self::BufferSize),
            "cov-increment" => Some(Self::CovIncrement),
            "database-revision" => Some(Self::DatabaseRevision),
            "date-list" => Some(Self::DateList),
            "deadband" => Some(Self::Deadband),
            "description" => Some(Self::Description),
            "effective-period" => Some(Self::EffectivePeriod),
            "enable" => Some(Self::Enable),
            "event-enable" => Some(Self::EventEnable),
            "event-state" => Some(Self::EventState),
            "event-time-stamps" => Some(Self::EventTimeStamps),
            "exception-schedule" => Some(Self::ExceptionSchedule),
            "firmware-revision" => Some(Self::FirmwareRevision),
            "high-limit" => Some(Self::HighLimit),
            "inactive-text" => Some(Self::InactiveText),
            "limit-enable" => Some(Self::LimitEnable),
            "list-of-object-property-references" => Some(Self::ListOfObjectPropertyReferences),
            "log-buffer" => Some(Self::LogBuffer),
            "log-device-object-property" => Some(Self::LogDeviceObjectProperty),
            "log-interval" => Some(Self::LogInterval),
            "low-limit" => Some(Self::LowLimit),
            "max-apdu-length-accepted" => Some(Self::MaxApduLengthAccepted),
            "max-pres-value" => Some(Self::MaxPresValue),
            "min-pres-value" => Some(Self::MinPresValue),
            "model-name" => Some(Self::ModelName),
            "notification-class" => Some(Self::NotificationClass),
            "notify-type" => Some(Self::NotifyType),
            "number-of-apdu-retries" => Some(Self::NumberOfApduRetries),
            "object-identifier" => Some(Self::ObjectIdentifier),
            "object-list" => Some(Self::ObjectList),
            "object-name" => Some(Self::ObjectName),
            "object-type" => Some(Self::ObjectType),
            "out-of-service" => Some(Self::OutOfService),
            "present-value" => Some(Self::PresentValue),
            "priority-array" => Some(Self::PriorityArray),
            "protocol-revision" => Some(Self::ProtocolRevision),
            "protocol-version" => Some(Self::ProtocolVersion),
            "recipient-list" => Some(Self::RecipientList),
            "record-count" => Some(Self::RecordCount),
            "reliability" => Some(Self::Reliability),
            "relinquish-default" => Some(Self::RelinquishDefault),
            "resolution" => Some(Self::Resolution),
            "schedule-default" => Some(Self::ScheduleDefault),
            "segmentation-supported" => Some(Self::SegmentationSupported),
            "start-time" => Some(Self::StartTime),
            "status-flags" => Some(Self::StatusFlags),
            "stop-time" => Some(Self::StopTime),
            "system-status" => Some(Self::SystemStatus),
            "time-delay" => Some(Self::TimeDelay),
            "total-record-count" => Some(Self::TotalRecordCount),
            "units" => Some(Self::Units),
            "update-interval" => Some(Self::UpdateInterval),
            "vendor-name" => Some(Self::VendorName),
            "weekly-schedule" => Some(Self::WeeklySchedule),
            _ => None,
        }
    }
}

impl core::fmt::Display for PropertyId {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::AckedTransitions => f.write_str("acked-transitions"),
            Self::ActiveText => f.write_str("active-text"),
            Self::ApduTimeout => f.write_str("apdu-timeout"),
            Self::ApplicationSoftwareVersion => f.write_str("application-software-version"),
            Self::BufferSize => f.write_str("buffer-size"),
            Self::CovIncrement => f.write_str("cov-increment"),
            Self::DatabaseRevision => f.write_str("database-revision"),
            Self::DateList => f.write_str("date-list"),
            Self::Deadband => f.write_str("deadband"),
            Self::Description => f.write_str("description"),
            Self::EffectivePeriod => f.write_str("effective-period"),
            Self::Enable => f.write_str("enable"),
            Self::EventEnable => f.write_str("event-enable"),
            Self::EventState => f.write_str("event-state"),
            Self::EventTimeStamps => f.write_str("event-time-stamps"),
            Self::ExceptionSchedule => f.write_str("exception-schedule"),
            Self::FirmwareRevision => f.write_str("firmware-revision"),
            Self::HighLimit => f.write_str("high-limit"),
            Self::InactiveText => f.write_str("inactive-text"),
            Self::LimitEnable => f.write_str("limit-enable"),
            Self::ListOfObjectPropertyReferences => {
                f.write_str("list-of-object-property-references")
            }
            Self::LogBuffer => f.write_str("log-buffer"),
            Self::LogDeviceObjectProperty => f.write_str("log-device-object-property"),
            Self::LogInterval => f.write_str("log-interval"),
            Self::LowLimit => f.write_str("low-limit"),
            Self::MaxApduLengthAccepted => f.write_str("max-apdu-length-accepted"),
            Self::MaxPresValue => f.write_str("max-pres-value"),
            Self::MinPresValue => f.write_str("min-pres-value"),
            Self::ModelName => f.write_str("model-name"),
            Self::NotificationClass => f.write_str("notification-class"),
            Self::NotifyType => f.write_str("notify-type"),
            Self::NumberOfApduRetries => f.write_str("number-of-apdu-retries"),
            Self::ObjectIdentifier => f.write_str("object-identifier"),
            Self::ObjectList => f.write_str("object-list"),
            Self::ObjectName => f.write_str("object-name"),
            Self::ObjectType => f.write_str("object-type"),
            Self::OutOfService => f.write_str("out-of-service"),
            Self::PresentValue => f.write_str("present-value"),
            Self::PriorityArray => f.write_str("priority-array"),
            Self::ProtocolRevision => f.write_str("protocol-revision"),
            Self::ProtocolVersion => f.write_str("protocol-version"),
            Self::RecipientList => f.write_str("recipient-list"),
            Self::RecordCount => f.write_str("record-count"),
            Self::Reliability => f.write_str("reliability"),
            Self::RelinquishDefault => f.write_str("relinquish-default"),
            Self::Resolution => f.write_str("resolution"),
            Self::ScheduleDefault => f.write_str("schedule-default"),
            Self::SegmentationSupported => f.write_str("segmentation-supported"),
            Self::StartTime => f.write_str("start-time"),
            Self::StatusFlags => f.write_str("status-flags"),
            Self::StopTime => f.write_str("stop-time"),
            Self::SystemStatus => f.write_str("system-status"),
            Self::TimeDelay => f.write_str("time-delay"),
            Self::TotalRecordCount => f.write_str("total-record-count"),
            Self::Units => f.write_str("units"),
            Self::UpdateInterval => f.write_str("update-interval"),
            Self::VendorName => f.write_str("vendor-name"),
            Self::WeeklySchedule => f.write_str("weekly-schedule"),
            Self::Proprietary(v) => write!(f, "proprietary-{v}"),
        }
    }
}
