/// BACnet property identifiers.
///
/// Common standard properties are named variants; vendor-specific or
/// unrecognised identifiers use [`Proprietary`](Self::Proprietary).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PropertyId {
    AckedTransitions,
    ActiveText,
    ApduTimeout,
    ApplicationSoftwareVersion,
    BufferSize,
    CovIncrement,
    DatabaseRevision,
    DateList,
    Deadband,
    Description,
    EffectivePeriod,
    Enable,
    EventEnable,
    EventState,
    EventTimeStamps,
    ExceptionSchedule,
    FirmwareRevision,
    HighLimit,
    InactiveText,
    LimitEnable,
    ListOfObjectPropertyReferences,
    LogBuffer,
    LogDeviceObjectProperty,
    LogInterval,
    LowLimit,
    MaxApduLengthAccepted,
    MaxPresValue,
    MinPresValue,
    ModelName,
    NotificationClass,
    NotifyType,
    NumberOfApduRetries,
    ObjectIdentifier,
    ObjectList,
    ObjectName,
    ObjectType,
    OutOfService,
    PresentValue,
    PriorityArray,
    ProtocolRevision,
    ProtocolVersion,
    RecipientList,
    RecordCount,
    Reliability,
    RelinquishDefault,
    Resolution,
    ScheduleDefault,
    SegmentationSupported,
    StartTime,
    StatusFlags,
    StopTime,
    SystemStatus,
    TimeDelay,
    TotalRecordCount,
    Units,
    UpdateInterval,
    VendorName,
    WeeklySchedule,
    Proprietary(u32),
}

impl PropertyId {
    pub const fn to_u32(self) -> u32 {
        match self {
            Self::AckedTransitions => 0,
            Self::ActiveText => 4,
            Self::ApduTimeout => 11,
            Self::ApplicationSoftwareVersion => 12,
            Self::BufferSize => 126,
            Self::CovIncrement => 22,
            Self::DatabaseRevision => 155,
            Self::DateList => 23,
            Self::Deadband => 25,
            Self::Description => 28,
            Self::EffectivePeriod => 32,
            Self::Enable => 133,
            Self::EventEnable => 35,
            Self::EventState => 36,
            Self::EventTimeStamps => 130,
            Self::ExceptionSchedule => 38,
            Self::FirmwareRevision => 44,
            Self::HighLimit => 45,
            Self::InactiveText => 46,
            Self::LimitEnable => 52,
            Self::ListOfObjectPropertyReferences => 78,
            Self::LogBuffer => 131,
            Self::LogDeviceObjectProperty => 132,
            Self::LogInterval => 134,
            Self::LowLimit => 59,
            Self::MaxApduLengthAccepted => 62,
            Self::MaxPresValue => 65,
            Self::MinPresValue => 69,
            Self::ModelName => 70,
            Self::NotificationClass => 17,
            Self::NotifyType => 72,
            Self::NumberOfApduRetries => 73,
            Self::ObjectIdentifier => 75,
            Self::ObjectList => 76,
            Self::ObjectName => 77,
            Self::ObjectType => 79,
            Self::OutOfService => 81,
            Self::PresentValue => 85,
            Self::PriorityArray => 87,
            Self::ProtocolRevision => 139,
            Self::ProtocolVersion => 98,
            Self::RecipientList => 102,
            Self::RecordCount => 141,
            Self::Reliability => 103,
            Self::RelinquishDefault => 104,
            Self::Resolution => 106,
            Self::ScheduleDefault => 174,
            Self::SegmentationSupported => 107,
            Self::StartTime => 142,
            Self::StatusFlags => 111,
            Self::StopTime => 143,
            Self::SystemStatus => 112,
            Self::TimeDelay => 113,
            Self::TotalRecordCount => 145,
            Self::Units => 117,
            Self::UpdateInterval => 118,
            Self::VendorName => 121,
            Self::WeeklySchedule => 123,
            Self::Proprietary(v) => v,
        }
    }

    pub const fn from_u32(value: u32) -> Self {
        match value {
            0 => Self::AckedTransitions,
            4 => Self::ActiveText,
            11 => Self::ApduTimeout,
            12 => Self::ApplicationSoftwareVersion,
            126 => Self::BufferSize,
            22 => Self::CovIncrement,
            155 => Self::DatabaseRevision,
            23 => Self::DateList,
            25 => Self::Deadband,
            28 => Self::Description,
            32 => Self::EffectivePeriod,
            133 => Self::Enable,
            35 => Self::EventEnable,
            36 => Self::EventState,
            130 => Self::EventTimeStamps,
            38 => Self::ExceptionSchedule,
            44 => Self::FirmwareRevision,
            45 => Self::HighLimit,
            46 => Self::InactiveText,
            52 => Self::LimitEnable,
            78 => Self::ListOfObjectPropertyReferences,
            131 => Self::LogBuffer,
            132 => Self::LogDeviceObjectProperty,
            134 => Self::LogInterval,
            59 => Self::LowLimit,
            62 => Self::MaxApduLengthAccepted,
            65 => Self::MaxPresValue,
            69 => Self::MinPresValue,
            70 => Self::ModelName,
            17 => Self::NotificationClass,
            72 => Self::NotifyType,
            73 => Self::NumberOfApduRetries,
            75 => Self::ObjectIdentifier,
            76 => Self::ObjectList,
            77 => Self::ObjectName,
            79 => Self::ObjectType,
            81 => Self::OutOfService,
            85 => Self::PresentValue,
            87 => Self::PriorityArray,
            139 => Self::ProtocolRevision,
            98 => Self::ProtocolVersion,
            102 => Self::RecipientList,
            141 => Self::RecordCount,
            103 => Self::Reliability,
            104 => Self::RelinquishDefault,
            106 => Self::Resolution,
            174 => Self::ScheduleDefault,
            107 => Self::SegmentationSupported,
            142 => Self::StartTime,
            111 => Self::StatusFlags,
            143 => Self::StopTime,
            112 => Self::SystemStatus,
            113 => Self::TimeDelay,
            145 => Self::TotalRecordCount,
            117 => Self::Units,
            118 => Self::UpdateInterval,
            121 => Self::VendorName,
            123 => Self::WeeklySchedule,
            v => Self::Proprietary(v),
        }
    }
}
